steps:
  # Day18: Artifact Registryå¿œç”¨ç®¡ç†
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
    - '-c'
    - |
      echo "ðŸ“Š Day18: Artifact Registryå¿œç”¨ç®¡ç†é–‹å§‹"
      
      # 1. ã‚«ã‚¹ã‚¿ãƒ ãƒ¬ãƒã‚¸ãƒˆãƒªä½œæˆ
      gcloud artifacts repositories create production-images \
        --repository-format=docker \
        --location=asia-northeast1 \
        --description="Day18å­¦ç¿’ç”¨ãƒ—ãƒ­ãƒ€ã‚¯ã‚·ãƒ§ãƒ³ãƒ¬ãƒã‚¸ãƒˆãƒª" || echo "âœ… æ—¢ã«å­˜åœ¨"
      
      # 2. æ—¢å­˜ã‚¤ãƒ¡ãƒ¼ã‚¸ã®åˆ†æž
      echo "ðŸ“ˆ æ—¢å­˜ã‚¤ãƒ¡ãƒ¼ã‚¸ã‚µã‚¤ã‚ºåˆ†æž:"
      gcloud artifacts docker images list \
        asia-northeast1-docker.pkg.dev/$$PROJECT_ID/cloud-run-source-deploy \
        --format="table(package,createTime,sizeBytes)"
      
      # 3. ã‚¯ãƒªãƒ¼ãƒ³ã‚¢ãƒƒãƒ—ãƒãƒªã‚·ãƒ¼ä½œæˆãƒ»é©ç”¨
      cat > /workspace/cleanup-policy.json << 'EOL'
      {
        "rules": [
          {
            "name": "keep-minimum-versions",
            "action": {"type": "Keep"},
            "mostRecentVersions": {"keepCount": 3}
          },
          {
            "name": "delete-old-versions",
            "action": {"type": "Delete"},
            "olderThan": "30d"
          }
        ]
      }
      EOL
      
      # ãƒãƒªã‚·ãƒ¼é©ç”¨ï¼ˆãƒ‰ãƒ©ã‚¤ãƒ©ãƒ³ï¼‰
      gcloud artifacts repositories set-cleanup-policies cloud-run-source-deploy \
        --location=asia-northeast1 \
        --policy=/workspace/cleanup-policy.json \
        --dry-run
      
      echo "âœ… Day18 Artifact Registryå¿œç”¨ç®¡ç†å®Œäº†"

  # å­¦ç¿’è¨˜éŒ²ã‚’GitHubã«è‡ªå‹•ã‚³ãƒŸãƒƒãƒˆ
  - name: 'gcr.io/cloud-builders/git'
    entrypoint: 'bash'
    args:
    - '-c'
    - |
      # Gitè¨­å®š
      git config user.email "shin1yokota@gmail.com"
      git config user.name "Cloud Build Auto"
      
      # Day18å­¦ç¿’è¨˜éŒ²ä½œæˆ
      mkdir -p daily-logs
      cat > daily-logs/day18-auto-$(date +%Y%m%d-%H%M).md << 'EOL'
      # Day18: Artifact Registryå¿œç”¨ç®¡ç†ï¼ˆè‡ªå‹•å®Ÿè¡Œï¼‰
      
      ## âœ… è‡ªå‹•å®Ÿè¡Œå®Œäº†é …ç›®
      - ã‚«ã‚¹ã‚¿ãƒ ãƒ¬ãƒã‚¸ãƒˆãƒªä½œæˆ: production-images
      - æ—¢å­˜ã‚¤ãƒ¡ãƒ¼ã‚¸åˆ†æžå®Ÿè¡Œ
      - ã‚¯ãƒªãƒ¼ãƒ³ã‚¢ãƒƒãƒ—ãƒãƒªã‚·ãƒ¼è¨­å®šï¼ˆãƒ‰ãƒ©ã‚¤ãƒ©ãƒ³ï¼‰
      
      ## ðŸ“Š å®Ÿè¡Œçµæžœ
      å®Ÿè¡Œæ™‚åˆ»: $(date)
      Cloud Build ID: $BUILD_ID
      
      ## ðŸŽ¯ æ¬¡ã®ã‚¹ãƒ†ãƒƒãƒ—
      - æ‰‹å‹•ã§ã®ã‚¤ãƒ¡ãƒ¼ã‚¸æœ€é©åŒ–
      - ã‚»ãƒžãƒ³ãƒ†ã‚£ãƒƒã‚¯ãƒãƒ¼ã‚¸ãƒ§ãƒ‹ãƒ³ã‚°å®Ÿè£…
      EOL
      
      # è‡ªå‹•ã‚³ãƒŸãƒƒãƒˆãƒ»ãƒ—ãƒƒã‚·ãƒ¥
      git add .
      git commit -m "ðŸ¤– Day18è‡ªå‹•å®Ÿè¡Œ: Artifact Registryå¿œç”¨ç®¡ç†

      âœ… Cloud Buildè‡ªå‹•å®Ÿè¡Œå®Œäº†:
      - production-imagesãƒ¬ãƒã‚¸ãƒˆãƒªä½œæˆ
      - æ—¢å­˜ã‚¤ãƒ¡ãƒ¼ã‚¸åˆ†æž
      - ã‚¯ãƒªãƒ¼ãƒ³ã‚¢ãƒƒãƒ—ãƒãƒªã‚·ãƒ¼è¨­å®š
      
      ðŸ• å®Ÿè¡Œæ™‚åˆ»: $(date)
      ðŸ†” Build ID: $BUILD_ID"
      
      git push origin main

options:
  logging: CLOUD_LOGGING_ONLY
